### ISSUE TITLE
Key generation can be nicer

### ISSUE THREAD

**Issue by varnav** [bngsudheer/ansible-role-dkim#1]
Now:

```
- name: Ensure signing key is present
  stat:
    path: "/etc/opendkim/keys/{{ dkim_selector }}.private"
  register: dkim_key

- name: Generate signing key
  shell: /usr/sbin/opendkim-genkey -s {{ dkim_selector }} -d {{ dkim_domains[0] }} -D /etc/opendkim/keys
  when: not dkim_key.stat.exists
  notify:
    - restart opendkim
  tags:
    - skip_ansible_lint
```

Can be:

```
- name: Generate signing key
  command: /usr/sbin/opendkim-genkey -s {{ dkim_selector }} -d {{ dkim_domains[0] }} -D /etc/opendkim/keys -b 1024
  args:
    creates: "/etc/opendkim/keys/{{ dkim_selector }}.private"
    warn: false
  notify:
    - restart opendkim
```
